output_dir: finalresults/ip_with_fake_edge_128

trainer:
    name: gnn_sparse

data:
    name: hitgraphs_sparse
    input_dir: results/ip_trigger_with_fake_edge
    n_train: 18000
    n_valid: 1800
    real_weight: 3
    batch_size: 128
    n_workers: 4

model:
    name: agnn
    input_dim: 3
    hidden_dim: 30
    hidden_activation: Tanh
    n_graph_iters: 8
    layer_norm: true
    loss_func: mse_loss

optimizer:
    name: Adam
    learning_rate: 0.0001
    weight_decay: 1.e-4
    lr_decay_schedule:
        - {start_epoch: 64, end_epoch: 128, factor: 0.1}

training:
    n_total_epochs: 500

