# input/output configuration
input_dir: datasets/ip_trigger
output_dir: results/ip_trigger
n_files: 19847

# Graph building configuration
selection:
    pt_min: -1 # GeV
    phi_slope_max: 0.1
    z0_max: 200
    n_phi_sections: 1
    n_eta_sections: 1
    eta_range: [-5, 5]
